application: project-alexa
version: 3
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /basic_sitemap.txt
  static_files: static/basic_sitemap.txt
  upload: static/basic_sitemap.txt

- url: /channel.html
  static_files: static/channel.html
  upload: static/channel.html

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: '2.6'

- name: django
  version: latest