courses = {"Musicianship": "Music",
"Music & Society": "Music",
"AP Music Theory": "Music",
"Advanced Problems in Music Theory": "Music",
"Class Piano": "Music",
"MIDI Workshop": "Music",
"Senior Music Seminar": "Music",
"AVPA Music Alliance 1 and 2": "Music",
"Honors Biology": "Science",
"Medical Science Seminar: Epidemiology": "Science",
"Medical Science Seminar: Pharmacology": "Science",
"Medical Science Seminar: Research": "Science",
"Biotechnology Lab": "Science",
"Advanced Biology": "Science",
"Anatomy and Physiology": "Science",
"Physiological Control Systems": "Science",
"AP Biology": "Science",
"AP Psychology": "Science",
"Anatomy and Physiology II": "Science",
"IB Environmental Systems and Society": "Science",
"Bioethics": "Science",
"Biopsychology": "Science",
"Botany": "Science",
"Developmental Biology": "Science",
"Introductory Anatomy and Physiology": "Science",
"Medical Microbiology": "Science",
"Psychology of the Individual": "Science",
"Cell Biology": "Science",
"ResMol": "Science",
"Topics in Oncology": "Science",
"Virology": "Science",
"Zoology": "Science",
"Advanced Business Topics 1": "Business",
"Advanced Business Topics 2": "Business",
"IB Microeconomics HL": "Business",
"IB Macroeconomics HL": "Business",
"Financial Markets & Trading Level I": "Business",
"Financial Markets & Trading Level II": "Business",
"Federal Reserve Bank Challenge": "Business",
"AP Microeconomics": "Business",
"AP Macroeconomics": "Business",
"Introduction to Business": "Business",
"Introduction to Business Law Elective": "Business",
"Stock Market": "Business",
"Management Information Systems I": "Business",
"Management Information Systems II": "Business",
"Introduction to Chemistry": "Science",
"Intermediate Chemistry": "Science",
"Honors Chemistry": "Science",
"Advanced Chemistry": "Science",
"AP Chemistry": "Science",
"Organic Chemistry I": "Science",
"Organic Chemistry II": "Science",
"Philosophy of Science": "Science",
"Kitchen Chemistry": "Science",
"Nanoscale Materials Science": "Science",
"Foundation of Nanotechnology": "Science",
"Introduction to Hospitality and Culinary Arts": "Culinary",
"Hotel Management & Culinary Theory": "Culinary",
"Entrepreneurship/ Advanced Culinary/Pastry Arts": "Culinary",
"Hospitality Management/ Advanced Culinary/Pastry Arts/ ServSafe": "Culinary",
"Introduction to Cake Decorating": "Culinary",
"Baking for the Holidays": "Culinary",
"Hors d'Oeuvres": "Culinary",
"All About Chocolate": "Culinary",
"World Cuisine": "Culinary",
"European Desserts": "Culinary",
"Classical French Cuisine": "Culinary",
"Healthy Cooking": "Culinary",
"Cooking for College": "Culinary",
"Sustainability Solutions": "Culinary",
"SkillsUSA Competitive Management": "Culinary",
"Introduction to Hotel Management": "Culinary",
"Health": "Health",
"Driver Education Theory": "Health",
"Family Living": "Health",
"Early America": "History",
"World History": "History",
"US History II": "History",
"IB History HL": "History",
"Spanish I/II": "Languages",
"Spanish II": "Languages",
"Spanish III": "Languages",
"Spanish IV": "Languages",
"Spanish V": "Languages",
"IB Spanish SL": "Languages",
"IB Spanish HL": "Languages",
"Theory and Practice of Human Rights": "Languages",
"Spanish Cinema": "Languages",
"Cultures of Spain and Latin America": "Languages",
"Pre-Engineering Competition": "Technology",
"Introduction to Nanotechnology": "Technology",
"Bio-Engineering": "Technology",
"Engineering Design and Development": "Technology",
"Manufacturing Process": "Technology",
"Civil Engineering and Architecture": "Technology",
"Principles of Engineering": "Technology",
"Introduction to Engineering Design II": "Technology",
"Introduction to Engineering Design I": "Technology",
"System Support and Maintenance": "Technology",
"Open Source and Mobile Application Development": "Technology",
"Programming I": "Technology",
"System Design Technology": "Technology",
"Mechatronics": "Technology",
"Introduction to Networking": "Technology",
"Digital Electronics": "Technology",
"Technology II for ATCS": "Technology",
"Engineering Technology I": "Technology",
"Experimental Technology": "Technology",
"AP Computer Science A": "Technology",
"WBCA-TV": "Technology",
"Advanced Animation": "Technology",
"Intermediate Animation": "Technology",
"Introduction to Animation": "Technology",
"Advanced Video Production": "Technology",
"Intermediate Video Production": "Technology",
"Introduction to Video Production": "Technology",
"Visual Technology II": "Technology",
"Technology II": "Technology",
"Technology I": "Technology",
"Introduction to Volcanoes": "Science",
"Earthquakes": "Science",
"Astronomy": "Science",
"Energy and Engineering": "Science",
"AP Physics C": "Science",
"AP Physics B": "Science",
"Honors Physics": "Science",
"IB Physics SL": "Science",
"Honors Physics": "Science",
"Intermediate Physics": "Science",
"Introductory Physics": "Science",
"Advanced Physics": "Science",
"Introduction to Microscopy": "Science",
"Data Structures": "Technology",
"Advanced Topics in Mathematics": "Math",
"Math Team II Elective": "Math",
"Math Team I Elective": "Math",
"Analytic Calculus BC+": "Math",
"Discrete Mathematics II": "Math",
"Discrete Mathematics I": "Math",
"Analysis 1": "Math",
"Algebra 2 and Trigonometry": "Math",
"Advanced Analysis II": "Math",
"SAT Math Workshop": "Math",
"Analysis II": "Math",
"Math Problem Seminar": "Math",
"Geometric Concepts": "Math",
"Calculus 1": "Math",
"Financial Mathematics": "Math",
"IB Mathematics SL": "Math",
"Statistics": "Math",
"Multivariable Calculus": "Math",
"AP Calculus BC": "Math",
"IB Mathematics HL": "Math",
"AP Statistics": "Math",
"Linear Algebra and Differential Equations": "Math",
"Advanced Analysis I": "Math",
"AP Calculus AB": "Math",
"Writing for Stage and Screen": "Literature",
"Women in Literature": "Literature",
"Women in Film": "Literature",
"Theory of Knowledge": "Literature",
"Studies in Drama": "Literature",
"Shakespeare Through Film": "Literature",
"Science Fiction as a Literary Genre": "Literature",
"Recycled Literature: Literary Genres and Popular Culture": "Literature",
"Poetry Seminar": "Literature",
"Mythology (Comparative)": "Literature",
"Humanities Research (Creative Writing II)": "Literature",
"Great Problems of Philosophy": "Literature",
"Introduction to Journalism": "Literature",
"Advanced Journalism Workshop": "Literature",
"Advanced Creative Writing Seminar": "Literature",
"Autobiographies: Writing the Self": "Literature",
"IB World Literature II HL": "Literature",
"World Literature II Honors": "Literature",
"IB World Literature I HL": "Literature",
"World Literature I Honors": "Literature",
"American Literature II Honors": "Literature",
"American Literature I Honors": "Literature",
"Intro to Mandarin I": "Languages",
"Mandarin IV": "Languages",
"Mandarin III": "Languages",
"Mandarin II": "Languages",
"Mandarin I": "Languages",
"IB French HL": "Languages",
"IB French SL": "Languages",
"French V": "Languages",
"French IV": "Languages",
"French III": "Languages",
"French II": "Languages",
"French I/II": "Languages",
"Foundations of Spanish": "Languages"}

from database import *
from google.appengine.api import memcache

for course in courses:
	group = courses[course].lower()
	si = SubjectIcons(subject=course, icon=group)
	si.put()

	memcache.set('icon-'+course, group)

#######

q = Guides.all()
for guide in q.run():
	subject = guide.subject

	icon = memcache.get('icon-'+subject)
	if not icon: # if icon not in memcache
		q = SubjectIcons.all()
		q.filter('subject =', subject)
		si = q.get()
		if not si: # if icon not in db
			icon = 'backpack' ##! change to default icon later
		else:
			icon = si.icon

	guide.icon = icon
	guide.put()